### ISSUE TITLE
Node has undefined callback parameter if a previous node returns an empty array

### ISSUE THREAD

**Issue by jingidy** [dfellis/queue-flow#11]
I have some code that looks like this: 

```
q([null]).node(generate array).node(do stuff)
```

When the first node generates an empty array, the 2nd node gets called with undefined parameters for both the args and the callback function. I would expect that the 2nd node doesn't get called, or gets called with undefined args and a defined callback.

Complete test case here: https://gist.github.com/jingidy/5879399

**Comment by dfellis** [comment]
I've added comments to your gist with the explanation, but the short answer is that `.node` uses an array value as a list of argument values to pass into the specified node-style function, so to actually pass an array as a single argument, you need to wrap it in another array.

The reason why no callback came was because queue-flow thought your method was synchronous since the argument length didn't match an argument length for an asynchronous call. You can override its guessing by using `.nodeAsync` or `.nodeSync`.

A fixed test case can be found here: https://gist.github.com/dfellis/5879675

**Comment by jingidy** [comment]
Thanks for the solution. I'm kind of confused about why it works though.

I thought since 
`[1, 2, 3] -> .node() = node(1), node(2), node(3)`, 
then
`[1, 2, 3] -> .map() = map(1), map(2), map(3)`.
but in your solution, it seems like `.map()` didn't get expanded?

**Comment by dfellis** [comment]
`q([1, 2, 3]) -> node(1), node(2), node(3)` and `q([1, 2, 3]) -> map(1), map(2), map(3)` are all correct.

But `q([[1], [1, 2], [1, 2, 3]])` is more interesting:

For map, it'd be `mapFunc([1]), mapFunc([1, 2]), mapFunc([1, 2, 3])`, for node it's `nodeFunc(1), nodeFunc(1, 2), nodeFunc(1, 2, 3)`, essentially.

The fact that you can have a nested array inside of the enqueued array is why `flatten` exists, if that's _not_ want you want.
