### ISSUE TITLE
examples/graph.js  fails

### ISSUE THREAD

**Issue by ghost** [dfellis/queue-flow#3]
.branch has replaced .chain  

https://github.com/dfellis/queue-flow/commit/3c3afa47e92140f61f8e675cdbb6973882ffe7df

**Comment by dfellis** [comment]
Oh, sorry I forgot to update that. I decided that `branch` could do double-duty and accept strings, arrays of strings, as well as functions and handle both use-cases for branching between queues. (Basically, I kept forgetting what I called "the other `branch`", so I thought if it was confusing to me, it'll definitely be confusing for others.)

I'll fix that shortly.

**Comment by dfellis** [comment]
Okay, that fixes `examples/graph.js` on my machine and has been published in version 0.5.25. If that takes care of things for you, please close this issue. :)

**Comment by ghost** [comment]
Thanks. And thanks for queue-flow. It's an elegant solution for async programming.  

One suggestion: while the docs are comprehensive in explaining and comparing queue-flow, I suspect that many programmers would appreciate a short page of cookbook-style examples.

**Comment by dfellis** [comment]
Thanks for the compliment. On your suggestion, I have been trying to do that sort of thing, with the examples directory and the [tutorial in particular](http://dfellis.github.com/queue-flow/2012/09/21/tutorial/), such as demonstrating how you can easily put in debugging statements between methods, like this:

``` js
q([value])
    .each(console.log) // value
    .map(just)
    .each(console.log) // just(value)
    .map(like)
    .each(console.log) // like(just(value))
    .map(so)
    .each(console.log) // so(like(just(value)))
```

in case you missed it (the beginning of the tutorial assumes you know essentially nothing about functional programming, and you may have skipped it).

Is there something in particular you're looking for, though? What kind of patterns do you want demonstrated in queue-flow? Since I'm so deep into it, I may not have the right perspective on what newcomers would find useful.

**Comment by ghost** [comment]
The docs and tutorials are very good at explaining the principles of queue-flow. And yet when I started using `.node` for a series of http calls and errors, it took a while to get a working example, for example, to see how the data was passed between steps or transformed by `.map`. Then it was perfectly clear, obvious even. So my suggestion is only to supplement the generic examples with typical uses. I will contribute a version of my code when I get further along.

**Comment by dfellis** [comment]
Thanks for the clarification, @irickt .

I'm thinking the [GitHub wiki](https://github.com/dfellis/queue-flow/wiki) is the best place for that sort of thing, since anyone can edit it by default. So to kick it off I added a small pattern for using queue-flow with `.on('data', callback), .on('end', callback)` event handler patterns in Node.js with [http.get](https://github.com/dfellis/queue-flow/wiki/http.get).

Feel free to add your own examples there. :+1:
