### ISSUE TITLE
Is this possible with queue-flow

### ISSUE THREAD

**Issue by nevf** [dfellis/queue-flow#5]
I'm developing an app that uses Node.js on the server and websockets/socketio etc to communicate with the browser.

In the browser I execute some code back in Node and when that completes it executes a function back in the browser. So what I want is to queue up these functions in the Browser as follows:
1. do some stuff
2. call function in Node
3. wait for Node to call function in browser
4. continue doing stuff.

I've read through the tutorial, but it isn't at all clear whether this is a valid use case. 

BTW Great work and great docs.

-Neville

**Comment by dfellis** [comment]
Hi Neville, thanks for the compliments.

What you're describing certainly seems doable with a queuing system like `queue-flow`, but I'm not sure if it's the right fit.

Do you need the guarantee of queue ordering for your functions, or are you just looking for a way to make sure that the functions making the remote call get the desired function's results back?

Basically, I'm wondering why `$.ajax('http://server.com/rest/interface').done(callback)` won't meet your needs?

If you do need a queue-ordering guarantee, is that global across all users or for each individual user?

These will all affect the architecture that's best for you, and there are _definitely_ situations where you **don't** want to use `queue-flow` -- for instance, any situation where you want a real-time guarantee (and it would be better for the client to re-try than wait for stale data to process if its been too long); true queues (not using [`sloppy-queue-flow`](https://github.com/dfellis/sloppy-queue-flow) or [`parallel-queue-flow`](https://github.com/dfellis/sloppy-queue-flow)) can have "clogging" issues if the processing time of queue elements are not predictable.

I'm saying this because I don't want you to think of this (or any) library as a golden gun.

If you give me a bit more info on what you're trying to accomplish, I can let you know whether the architecture you've described above makes sense. :)

David

**Comment by nevf** [comment]
Hi David,
Thanks for the detailed response. I do need a guarantee of queue order. At step 4 I need to access variables set at step 1. And yes multiple queues could be active at any point in time. I think this is a difficult problem to solve using queuing.  

In the end what I've done is pass the variables (JSON) set at step 1 to the server at step 2, which sends them back again at step 3 so they are available at step 4. This works perfectly and ensures the correct data is always processed when there are multiple calls to the server. 

I was interested to see if a queuing solution was possible, more out of interest than absolute need.

Neville
