### ISSUE TITLE
unexpected behavior when calling .node(...) (async autodetection fail)

### ISSUE THREAD

**Issue by pk11** [dfellis/queue-flow#6]
Hi, 

node 0.8.17
queue-flow 0.5.32

I am not sure if it's a bug but

given:

``` javascript
var q = require('queue-flow');
var fs = require('fs');

q(['.'])
    .node(fs.readdir, 'error')
    .flatten()
    .map(function(filename) {
        return ['./' + filename, 'utf8'];
    })
    .node(fs.readFile, 'error')
    .reduce(function(concat, fileData) {
        return concat + fileData;
    }, function(result) {
        console.log(result);
    }, '');
q('error')
.each(function(errorOut) {
  console.log(errorOut);
});
```

the output contains a bunch of `undefined` strings combined instead of the content of the files in the current directory.

 Based on the docs, my expectation would be that `fs.readFile` is invoked  multiple times with arguments supplied by `map`.

Could you please tell what I am doing wrong?

**Comment by pk11** [comment]
just for the record, looks like passing  the optional parameter 'utf8' to fs.readFile caused the problem (on OS X).

**Comment by dfellis** [comment]
Yes, I was about to mention that. The issue is this:

``` js
> var fs = require('fs');
undefined
> fs.readFile.length
2
> 
```

(Taken from the Node REPL) Because `fs.readFile` takes an optional argument and only defines two arguments in its function definition, queue-flow assumes the last argument is the callback if you provide `numArgs - 1` inputs, and assumes that the function is synchronous if you provide `numArgs` inputs.

The _actual_ solution in this case is to specify async manually.

``` js
q(['.'])
    .node(fs.readdir, 'error')
    .flatten()
    .map(function(filename) {
        return ['./' + filename, 'utf8'];
    })
    .nodeAsync(fs.readFile, 'error')
    .reduce(function(concat, fileData) {
        return concat + fileData;
    }, function(result) {
        console.log(result);
    }, '');
```

I'm sorry you ran into one of the corner cases where the auto-detection of sync/async methods failed, but Javascript has no annotations for functions and this was the best that I could come up with.

If you have ideas on how to avoid this, feel free to discuss them here. :) I'm reopening this issue and altering the title a bit.

**Comment by pk11** [comment]
thanks for the prompt answer and the clarification! I actually ran into another issue about queue-flow (and parallel-queue-flow) when trying to convert a project from `Step`. Is there a mailing list for your project? 

Thanks again.

**Comment by dfellis** [comment]
No, not at the moment. I'm subscribed to some mailing lists, myself, but I've been debating whether they're actually necessary in the age of GitHub.

Actual questions where code doesn't seem to work as expected _should_ be issues. They point out weaknesses in the API or documentation, at the least, and bugs to fix at the worst. For instance, I think I need to update the docs to make the async/sync detection algorithm better known and how you can override it with `<foo>Sync`/`<foo>Async`.

The other things mailing lists tend to house, such as general questions on whether or not the library is a good fit for a particular project belong in an FAQ that can go in the GitHub wiki, and other things like announcements of related/derivative/competing libraries can go there, as well. I think I'll go add some structure to this wiki for that purpose.

EDIT: Finally, GitHub automatically emails me when new issues are opened on the project (and anyone else who is watching the repo [not just starred it]), so that takes care of essentially everything a mailing list does, while keeping it more open and accessible to newbies (by keeping it more closely associated with the code, itself).

**Comment by pk11** [comment]
thanks! I just posted my question as an issue. I hope it makes sense.

**Comment by thosmos** [comment]
This seems to still be an issue with 0.6.3:

This code fails but works if changed to a named queue.

``` javascript
var cmd = {test1: "value1", test2: "value2"};

q([cmd])
.node(function(c, cb){
  setTimeout(function(){
    console.log("cmd1: " + JSON.stringify(c));
    cb(null, c);
  }, 1000);
}, 'error')
.node(function(c, cb){
  setTimeout(function(){
    console.log("cmd2: " + JSON.stringify(c));
    cb(null, c);
  }, 1000);
}, 'error')
.node(function(c, cb){
  setTimeout(function(){
    console.log("cmd3: " + JSON.stringify(c));
    cb(null, c);
  }, 1000);
}, 'error')
.each(console.log);
```

Only outputs the following: 

``` javascript
cmd1: {"test1":"value1","test2":"value2"}
cmd2: {"test1":"value1","test2":"value2"}
```

If changed to a named queue and called like so: 

``` javascript
q('nodetest').push(cmd);
```

It outputs:

``` javascript
cmd1: {"test1":"value1","test2":"value2"}
cmd2: {"test1":"value1","test2":"value2"}
cmd3: {"test1":"value1","test2":"value2"}
{ test1: 'value1', test2: 'value2' }
```

**Comment by dfellis** [comment]
You're right, going to re-open this. The 'close' command is propagating down the chain of objects before the final value in the queue is finished processing.

Just confirmed your code is failing in both 0.6.3 and 0.5.33, so its not a regression like I originally suspected.

**Comment by dfellis** [comment]
@thos37 Very sorry about how long this took to fix. Job, child, etc, etc.

Please confirm that it works for you, too. I added in a new test based on your test case, but it's possible that your actual usage here is slightly different and not covered.

Will publish as 0.6.7 when you give me the go-ahead. :)

**Comment by thosmos** [comment]
@dfellis  Looks good to me.  Thanks for the fix!

**Comment by dfellis** [comment]
Great! Publishing now. :)
